server:
  port: 2003

spring:
  application:
    name: seata-account-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    alibaba:
      seata:
        tx-service-group: demon_tx_group
  datasource:
    username: root
    password: 1234567
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///seata_account?serverTimezone=UTC

feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: info

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.demon.springcloud.domain