server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_route # 路由 id
          # uri: http://localhost:8001 # 提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/** # 断言

        - id: payment_route2
          # uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**
            # - After=2020-12-15T11:38:30.074+08:00[Asia/Shanghai]
            # - Cookie=username,demon
            # - Header=X-Request-Id, \d+
            # - Host=**.demon.org, **.demon.com
            # - Method=POST
            # - Query=username, \d+

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

