server:
  port: 83

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

# 消费者访问的微服务名称
service-url:
  nocas-user-service: http://nacos-payment-provider